name:                hrubric
version:             0.1.0.0
github:              "RobinWebbers/hrubric"
license:             BSD3
author:              "Robin Webbers"
maintainer:          "robin_webbers_1@hotmail.com"
copyright:           "2022 Robin Webbers"

category:            Testing
synopsis:            Auto-grade support for Hspec

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/RobinWebbers/HRubric#readme>

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.10.6
- mtl

library:
  source-dirs: src

tests:
  HRubric-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hrubric
    - hspec
