resolver: ghc-9.2.8

packages:
- .

extra-deps:
- hspec-2.10.6
- hspec-core-2.10.6
- hspec-discover-2.10.6
- hspec-expectations-0.8.2
- QuickCheck-2.14.3
- HUnit-1.6.2.0
- ansi-terminal-1.0
- call-stack-0.4.0
- random-1.2.1.1
- splitmix-0.1.0.4
- ansi-terminal-types-0.11.5
- colour-2.3.6
- quickcheck-io-0.2.0
- setenv-0.1.1.3
- tf-random-0.5
- primitive-0.8.0.0
- data-array-byte-0.1.0.1
